DROP TABLE IF EXISTS CAR;
CREATE TABLE CAR (
CAR_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
BRAND varchar(20) NOT NULL,
RELEASE_YEAR int NOT NULL,
COST int NOT NULL,
CREATED_DATE datetime NOT NULL,
PRIMARY KEY (CAR_ID)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

