DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS(
ID INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
CITY VARCHAR(20) NOT NULL,
STREET VARCHAR(20) NOT NULL,
HOUSE VARCHAR(5) NOT NULL,
PRIMARY KEY (ID)
)ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;